### ISSUE TITLE
Warning on adding image to idea, (not when editing)

### ISSUE THREAD

**Issue by phillimorland** [liqd/zt-app#243]
Current warning when adding an image, does not stop image adding but must be tested further on dev as currently doesn'T seem possible: 
```
[Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'imageObj.uri.match')]
at components/imageFormField.js:17:4 in mutateImageProps
at components/imageFormField.js:37:20 in pickImage
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

initial error when adding image - does not seem to be triggered in recent testing

```
An unhandled error was caught from submitForm(), [TypeError: undefined is not an object (evaluating 'iter[Symbol.iterator]')]
at node_modules/formik/dist/formik.cjs.development.js:928:17 in useEventCallback$argument_0
at [native code]:null in flushedQueue
at [native code]:null in callFunctionReturnFlushedQueue
```

**Comment by phillimorland** [comment]
closed in favour of more precise https://github.com/liqd/zt-app/issues/248
